In [11]:
import numpy as np
deful = np.zeros(shape=(4,6),dtype=np.int32)
print(deful)
print(type(deful))
deful.dtype

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
<class 'numpy.ndarray'>


dtype('int32')

In [12]:
# defult by 1
once_arr = np.ones((4,3),dtype=np.int32)
once_arr

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [13]:
# full by a specific values
fill_s = np.full((3,4),4)
fill_s

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [ ]:
# find a number in array
arr = np.array([1,2,3,4,5,6,7,89,8,7,5,4,3,221])
# find 89
89 in arr
if 89 in arr:
    pass

<method-wrapper '__index__' of numpy.ndarray object at 0x000002060E6FF810>


In [22]:
sm = arr.sum()

sum(arr)
arr.mean()
print(sm)

365
