In [19]:
import numpy as np
matrix = np.array([[12,3,45],
                    [2,12,3],
                    [1,4,5],
                    [1,2,3,],[1,3,4]])
print(matrix.dtype)

int64


In [16]:
print(matrix*5)

[[ 60  15 225]
 [ 10  60  15]
 [  5  20  25]
 [  5  10  15]
 [  5  15  20]]


In [23]:
# creating a list from python list
list=[1,2,3,3,6,4]
list_arr= np.array(list)
list_arr.dtype
type(list_arr)

numpy.ndarray

In [24]:
ar=np.array((1,2,3,4,6,7,8))